name: continuous-integration
on: [push]
jobs:
  check_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
      - run: go build -v ./...
